# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTTP-Request-AsCGI
version:      0.1
version_from: lib/HTTP/Request/AsCGI.pm
installdirs:  site
requires:
    Carp:                          0
    Class::Accessor:               0
    File::Temp:                    0.14
    IO::Handle:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
